/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics Summary */
        get: operations["get_analytics_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Notification Status */
            notification_status: string;
            /** Acknowledged By */
            acknowledged_by: string | null;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Response Time S */
            response_time_s: number | null;
        };
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** Total Events */
            total_events: number;
            /** Confirmed */
            confirmed: number;
            /** Cancelled */
            cancelled: number;
            /** Alerts Open */
            alerts_open: number;
            /** Alerts Acknowledged */
            alerts_acknowledged: number;
            /** Alerts Dismissed */
            alerts_dismissed: number;
            /** Alerts Escalated */
            alerts_escalated: number;
            /** Response Time Avg S */
            response_time_avg_s: number;
            /** Response Time Median S */
            response_time_median_s: number;
            /** Response Time P95 S */
            response_time_p95_s: number;
            /** Notification Failures */
            notification_failures: number;
            /** False Positive Feedback Count */
            false_positive_feedback_count: number;
        };
        /** AuthLoginData */
        AuthLoginData: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /** Id */
            id: string;
            /** Device Name */
            device_name: string;
        };
        /** Event */
        Event: {
            /** Id */
            id: string;
            /** State */
            state: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Grace Deadline
             * Format: date-time
             */
            grace_deadline: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolved By */
            resolved_by: string | null;
            subject: components["schemas"]["SubjectInfo"];
            device: components["schemas"]["DeviceInfo"];
            /** Confidence */
            confidence: number;
            /** Confidence Calibrated */
            confidence_calibrated: boolean;
            /** Tier */
            tier: string;
            /** Track Id */
            track_id: number;
            /** Model Version */
            model_version: string;
            /** Feature Version */
            feature_version: string;
            /** Pose Quality */
            pose_quality: number;
            evidence: components["schemas"]["Evidence"];
            alert: components["schemas"]["Alert"] | null;
            /** Notifications */
            notifications: components["schemas"]["Notification"][];
            /** Feedback */
            feedback: components["schemas"]["Feedback"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** Evidence */
        Evidence: {
            /** Rapid Motion */
            rapid_motion: boolean;
            /** Orientation Change */
            orientation_change: number;
            /** Body Height Change */
            body_height_change: number;
            /** Post Event Stillness */
            post_event_stillness: boolean;
            /** Evidence Summary */
            evidence_summary: string;
        };
        /** Feedback */
        Feedback: {
            /** Caregiver Id */
            caregiver_id: string;
            /** Label */
            label: string;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Notification */
        Notification: {
            /** Channel */
            channel: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Last Attempt At */
            last_attempt_at: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /** PaginatedAlerts */
        PaginatedAlerts: {
            /** Items */
            items: components["schemas"]["Event"][];
            /** Total */
            total: number;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** PaginatedEvents */
        PaginatedEvents: {
            /** Items */
            items: components["schemas"]["Event"][];
            /** Total */
            total: number;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** SubjectInfo */
        SubjectInfo: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Location Label */
            location_label: string;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Note */
            note: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Must Change Password */
            must_change_password: boolean;
            /** Assigned Subject Ids */
            assigned_subject_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_analytics_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
    get_events_api_v1_events_get: {
        parameters: {
            query?: {
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEvents"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlerts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
